name: Deploy to Raspberry Pi with Docker
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Log into Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build Docker Image
        run: docker buildx create --use --name panliyong-portfolio && docker buildx inspect --bootstrap && docker buildx build --platform linux/amd64,linux/arm64/v8 -t panliyong/portfolio --push .

      - name: List Docker Images
        run: docker images
      - name: Push Docker Image
        run: docker push panliyong/portfolio

      - name: SSH in Pi and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            docker pull panliyong/portfolio
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 3000:3000 panliyong/portfolio
