name: Deploy to Raspberry Pi with Docker
on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Build Docker Image
        run: docker buildx create --use && docker buildx inspect --bootstrap && docker buildx build --platform linux/amd64,linux/arm64/v8 -t panliyong/portfolio .

      - name: Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker buildx create --use && docker buildx inspect --bootstrap && docker buildx build --platform linux/amd64,linux/arm64/v8 -t panliyong/portfolio .
          docker push panliyong/portfolio

      - name: SSH in Pi and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            docker buildx create --use && docker buildx inspect --bootstrap && docker buildx build --platform linux/amd64,linux/arm64/v8 -t panliyong/portfolio .
            docker pull panliyong/portfolio
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 3000:3000 panliyong/portfolio
