name: Deploy to Raspberry Pi with Docker
run-name: Testing if Docker works
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Build Docker Image
        run: docker build -t panliyong/portfolio

      - name: Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push panliyong/portfolio
