name: Deploy to Raspberry Pi with Docker
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Multi-Arch Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/portfolio:latest \
            --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH in Pi and Pull & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            docker pull --platform linux/arm64 panliyong/portfolio
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d --name portfolio -p 3000:3000 panliyong/portfolio
